export const SET_USER_DATA = "SET_USER_DATA";

export const USER_DATA = "USER_DATA";


export const RESET_SIGNUP="RESET_SIGNUP"

export const LOGGED_IN="LOGGED_IN"

export const SET_LOADING="SET_LOADING"
export const SET_ALERT="SET_ALERT"

export const SET_BOOKING_DATA="SET_BOOKING_DATA"

export const SET_MAP_DATA="SET_MAP_DATA"
export const SET_ENABLED_HOME="SET_ENABLED_HOME"

export const SET_BOTTOM_SHEET_INDEX="SET_BOTTOM_SHEET_INDEX"

export const SHOW_BOTTOM_SHEET="SHOW_BOTTOM_SHEET"

export const SET_NOTIFY="SET_NOTIFY"

export const SET_USER_VEHICLE_DATA="SET_USER_VEHICLE_DATA"

export const SET_INTIAL_BOOKING_DATA="SET_INTIAL_BOOKING_DATA"

export const SET_NOTIFICATIONS="SET_NOTIFICATIONS"

export const SET_NOTIFICATION_SEEN="SET_NOTIFICATION_SEEN"
